-- Add new fields to reservations table for enhanced functionality
ALTER TABLE reservations
  ADD COLUMN IF NOT EXISTS pdj_inclus BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS type_reservation ENUM('BOOKING', 'ON_SITE') NOT NULL DEFAULT 'BOOKING',
  ADD COLUMN IF NOT EXISTS laundry_included BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS laundry_price BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS manual_price BIGINT NOT NULL DEFAULT 0;

-- Add quantity field to equipments table
ALTER TABLE equipments
  ADD COLUMN IF NOT EXISTS quantite INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_consumable BOOLEAN NOT NULL DEFAULT FALSE;

-- Add collaboration dates to maintenance_workers table
ALTER TABLE maintenance_workers
  ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS id_photo_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS contract_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS quote_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS time_slot VARCHAR(100) NULL;

-- Update housekeeping task types
ALTER TABLE housekeeping_tasks
  MODIFY COLUMN type_tache ENUM('POST_OCCUPANCY', 'AFTER_OCCUPANCY', 'DEEP_CLEANING', 'EXCEPTIONAL', 'CHAMBRE','ESCALIER_RAMPE','DECORATIONS','MUR','PLAFOND','SOL_MOQUETTE','MEUBLES','COULOIR','TERASSE','TOILETTES') NOT NULL;
